//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TENS_proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.ControlSignosVitales = new HashSet<ControlSignosVitales>();
            this.DispositivoInvasor = new HashSet<DispositivoInvasor>();
            this.ficha_paciente = new HashSet<ficha_paciente>();
            this.Medicamento = new HashSet<Medicamento>();
            this.Programacion_Aseo = new HashSet<Programacion_Aseo>();
        }
    
        public int ID_paciente { get; set; }
        public Nullable<int> ID_persona2 { get; set; }
        public string enfermedad { get; set; }
        public string antecedentes { get; set; }
        public Nullable<int> peso { get; set; }
        public string alergias { get; set; }
        public string prescripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlSignosVitales> ControlSignosVitales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DispositivoInvasor> DispositivoInvasor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ficha_paciente> ficha_paciente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicamento> Medicamento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Programacion_Aseo> Programacion_Aseo { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
