//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TENS_proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class TENS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TENS()
        {
            this.ficha_paciente = new HashSet<ficha_paciente>();
        }
    
        public int ID_tens { get; set; }
        public Nullable<int> ID_persona1 { get; set; }
        public string contrasena { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ficha_paciente> ficha_paciente { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
