//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TENS_proyecto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TENSEntidades : DbContext
    {
        public TENSEntidades()
            : base("name=TENSEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ControlSignosVitales> ControlSignosVitales { get; set; }
        public virtual DbSet<DispositivoInvasor> DispositivoInvasor { get; set; }
        public virtual DbSet<ficha_paciente> ficha_paciente { get; set; }
        public virtual DbSet<Medicamento> Medicamento { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Programacion_Aseo> Programacion_Aseo { get; set; }
        public virtual DbSet<TENS> TENS { get; set; }
    }
}
